# Generated by Django 5.1.4 on 2024-12-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_packages/', verbose_name='Imagem')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Original')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto')),
                ('final_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
            ],
            options={
                'verbose_name': 'Pacote de Viagem',
                'verbose_name_plural': 'Pacotes de Viagem',
                'db_table': 'travel_packages',
            },
        ),
    ]
