# Generated by Django 4.2.17 on 2025-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_packages', '0001_travel_packages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpackages',
            options={'verbose_name': 'Pacote de Viagem', 'verbose_name_plural': 'Pacotes de Viagens'},
        ),
        migrations.AddField(
            model_name='travelpackages',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
